### ISSUE TITLE
could svg() take dot file/text and display svg image in browser

### ISSUE THREAD

**Issue by kangaroolab** [svgdotjs/svgdotjs.github.io#104]
could it possible to use svg() doing sth below (the example is with d3_graphviz?

```
const digraphText = `
digraph G {
  edge [ arrowtail = "none" arrowhead = "open" ]
  "part2" -> "ends?"
  "part2" -> "ends?"
  "part2" -> "small?"
  "-main" -> "part2"
  "-main" -> "part2"
  "-main" -> "part2"
  "-main" -> "bench"
  "-main" -> "part2"
  "-main" -> "parse"
}
`;
d3.select("#graph")
 .graphviz()
   .renderDot(digraphText);
```

**Comment by Fuzzyma** [comment]
This is the svg.js repo. I think you are looking for the d3.js repo.
However, your question seems more suitable for stackoverflow anyway

**Comment by kangaroolab** [comment]
thanks...just to confirm - svg.js can't take a dot file and draw it out as svg right? it would be nice if svg() can take dot file like how it takes svg tag

**Comment by Fuzzyma** [comment]
No, why would it? Svg.js understands svg. You basically invented a new format and expect it to work.
Parse and convert it yourself and then you can go and draw it with d3 or svg.js

**Comment by kangaroolab** [comment]
thanks. it is a not a few format but a well defined (see https://graphviz.org/doc/info/lang.html)
