### ISSUE TITLE
`SVG.Number` instead of `SVG.Point` in one of the examples

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svgdotjs.github.io#17]
I made a mistake in #16 and use `SVG.Number` instead of `SVG.Point` in one of the examples. Just leaving a reminder here...

**Comment by dotnetCarpenter** [comment]
Here: http://svgjs.com/classes/#svg-point

>clone()
>
>returns SVG.Point
>
>Get a new SVG.Point with the same x/y value.
>
> `var newPoint = new SVG.Number(1,1).clone()`

also, the heading anchor doesn't work if we have the same heading in multiple places on a page.

**Comment by wout** [comment]
Fixed!
