### ISSUE TITLE
Document that the DOM has to be ready before manipulating via svg.js

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svgdotjs.github.io#20]
>This is more of an observation than an issue.
I should have known better, but I initially included the JavaScript calling SVG in the head of my HTML. This fails. I began troubleshooting using different load events. I eventually figured out that it ran fine when I included my JavaScript at the end of the body instead of the head. I don't recall seeing this anywhere in the documentation.
Not a big deal but could save future developers a little headache if examples show this explicitly.

Ref: https://github.com/svgdotjs/svg.js/issues/712

**Comment by dotnetCarpenter** [comment]
Something like:
```js
function main() {
  var draw = SVG('drawing')
}

document.addEventListener('DOMContentLoaded', main, false)
// OR
$(document).ready(main)
```

**Comment by wout** [comment]
I added this in Getting Started as:

```js
SVG.on(document, 'DOMContentLoaded', function() {
  var draw = SVG('drawing')
})
```
