### ISSUE TITLE
Error in svgjs.com/classes/#multiply

### ISSUE THREAD

**Issue by kai-dj** [svgdotjs/svgdotjs.github.io#23]
it sais `matrix.matrix(matrix2)` - should be `matrix.multiply(matrix2)`

**Comment by Fuzzyma** [comment]
thanks! Feel free to create a PR to fix :)

**Comment by kai-dj** [comment]
Done. (Ihope - my first PR ^^)

**Comment by Fuzzyma** [comment]
Awesome!
