### ISSUE TITLE
Split docs into different versions

### ISSUE THREAD

**Issue by wout** [svgdotjs/svgdotjs.github.io#25]
I already started on the <strike>2.6</strike> 2.7 version of our docs, but here is a recap of things that I still need to do.

- [x] Make a separate branch for <strike>2.6</strike> 2.7
- [x] Add [Github redirects](https://stackoverflow.com/questions/10178304/what-is-the-best-approach-for-redirection-of-old-pages-in-jekyll-and-github-page) to current docs to start re-indexing for search engines
- [x] Make separate branch for 3.0
- [x] Add Algolia meta tags for version separation in search (1)
- [x] Create a PR for modified Algolia search settings (2)
- [x] Modify Algolia JS snippet (3)

### 1. Meta tags

> In order to have something that will scale and that will be exhaustive, I would recommend you to add some meta tags within your pages. These meta tags will give the context of the page to every extracted records, that is to stay their version. It should look this way:

```html
<meta name="docsearch:version" content="2.7">
```

> The "content" value will be implicitly added to every records extracted from the page.

### 2. Search settings

> You will need to do a PR of [your configuration file](https://github.com/algolia/docsearch-configs/blob/master/configs/svgjs.json) with the following parameter:

```json
"custom_settings": {
  "attributesForFaceting": [
    "version"
  ]
}
```
> You will leverage the [faceting feature of Algolia](https://www.algolia.com/doc/guides/searching/faceting/#faceting-overview).

### 3. JS snippet

> Once this PR will be merged and deployed, you will need to update the Javascript snippet already included in your website:

```html
<script type="text/javascript"> docsearch({
  apiKey: 'a01bac6cbc400d1cd9b3ae22bb918066',
  indexName: 'svgjs',
  inputSelector: '#agolia',
  algoliaOptions: { 'facetFilters': ["version:$VERSION"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

> The $VESION placeholder should be replaced by the `content` value of your meta tag. This update must be done once the crawl will be updated. That is to say within 24h after the PR being merged. Most of the time, a PR merged is deployed straight away.

**Comment by Fuzzyma** [comment]
Give me a short notice, when I can do something. Dont want to change something while you are working on it

**Comment by Fuzzyma** [comment]
@wout I just realized that publishing a 2.7 wasnt the best idea to do. Now we need a 2.7 branch :(.
I wanted to round up 2.x and publish a last release which fixes a few issues which popped up so that people have a fix without needing to upgrade right away. I hope it isnt much extra work now

**Comment by wout** [comment]
Don’t worry, I’ll just move everything from 2.6 to 2.7. Good thing I didn’t already set the redirects in motion.

**Comment by wout** [comment]
This is now implemented:

https://svgjs.com/docs/2.7/index.html
https://svgjs.com/docs/3.0/index.html

**Comment by wout** [comment]
Algolia search has already picked up the new structure for the 2.7 version, but not for 3.0. I'll keep an eye on it in the following days.

@Fuzzyma how do we proceed with changes in the 3.0 docs? I can write them but you'll need to give me some pointers. Maybe create an issue, section per section, for every part that needs to be added/modified/deleted?

**Comment by Fuzzyma** [comment]
@wout jeah no problem with that. I would like to open issues for every point in the changelog. That would it make easier for me to follow along. Is that okay?

**Comment by wout** [comment]
Perfect!

**Comment by Fuzzyma** [comment]
Ooooooooooook - that was more work expected!!
@wout since I opened the issues one after another the most relevant issue is the one with the lowest number
