### ISSUE TITLE
Document SVG.adopt

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svgdotjs.github.io#6]
In the documentation, http://svgjs.com/referencing/, there was no way of referencing an existing element. 

It would be appropriate to add a section on SVG.adopt to the [reference documentation](http://svgdotjs.github.io/referencing/).

> *@nickbreaton would be more than happy to submit a PR.*

Ref: https://github.com/svgdotjs/svg.js/issues/639

**Comment by wout** [comment]
Thanks!
