### ISSUE TITLE
`SVG.on()` calls the listener in the context of the passed object. el.on always uses the svg.js object as context

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svgdotjs.github.io#61]
so  in case of `SVG.on(node, 'event', fn)`, fn will be called in the context of node.
However `SVG.on(element, 'event', fn)` will call it in context of the element

**Comment by wout** [comment]
In the current docs, `el.on()` van also be passed a third argument:

> Note: The context of this in the callback is bound to the element. You can change this context by applying your own object:
> 
> `element.on('click', click, window) // context of this is window`

So it's not always the context of the element, right? I suppose and instance of `SVG.Element`, that will work as well?

**Comment by Fuzzyma** [comment]
Yes you can change the context by passing a custom binding. This issue however is about the default context which is used (in case no other context is passed).
This default context is always the svg object when you use `el.on()`. However it defaults to the passed object when called with `SVG.on()`.

So `SVG.on(rectNode, ...)` will call the handler in the context of the rectNode while `SVG.on(svgjsobj, ...)` will call it in the context of the object.
