### ISSUE TITLE
`SVG.on()/off()` and `el.on()/off()` now accepts an Array or multiple comma or space separated events e.g. "mousedown, foo bar"

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svgdotjs.github.io#62]
`el.on(['name1', 'name2'])`

or

`el.on('name1 name2')`

**Comment by wout** [comment]
Done. I will publish once I finished a series of them.

**Comment by Fuzzyma** [comment]
Actually that one was backported to svg.js v2.7 to solve a memory leak. So you can reuse that there
