### ISSUE TITLE
SVG attr()

### ISSUE THREAD

**Issue by mieszczans** [svgdotjs/svgdotjs.github.io#72]
```
Element.attr({
'fill': '#000'
});
```
It doesn't work on IE 11/Edge 42 and in compatybility you tell us as it is:
Desktop:
Firefox 3+
Chrome 4+
Safari 3.2+
Opera 9+
IE9+

**Comment by Fuzzyma** [comment]
What version of svg.js are you using? I tested it and it surely works. So a better error description would be nice. What is the resulting svg? Does it show you what you want, when you write the svg code in the html directly?

**Comment by mieszczans** [comment]
Sorry I had wrong color format so that was the issue.
