### ISSUE TITLE
SVG is not rendering in IE11

### ISSUE THREAD

**Issue by mieszczans** [svgdotjs/svgdotjs.github.io#73]
1.Everything is working fine in Edge/Chrome but not in IE 11. I had error:
'Access denied' but I used Angular DOMSanitizer.
Sometimes I need to reset my svg so I inner empty string. So I used Angular sanitize method with arguments: (SecureContent.NONE, ''). Now error is not displaying in the console but svg still not rendering. When I look into devTools I see that my div is empty. Can you help me with that?
2. Where I can find your bundle with polyfills?

**Comment by Fuzzyma** [comment]
Please stop posting issues in the documentation repository. Post in the actual code repository instead please.

To make svg.js 3.0 work in Chrome you need to include the poly fills which are distributed with the package. We do not include polyfills anymore. If you need support for old browser (especially ie11) include both polyfills

**Comment by saivan** [comment]
I’ll go ahead and close this. For anything else, please use the main repo :)
