### ISSUE TITLE
svgjs.com down

### ISSUE THREAD

**Issue by d4h0** [svgdotjs/svgdotjs.github.io#87]
It seems the website is down. Are you guys aware of this?

It seems there were a few changes to the website recently. Maybe one of these changes broke something.

For people who need to read some of the documentation:

You can find it in markdown format in the following folder:

https://github.com/svgdotjs/svgdotjs.github.io/blob/source-3.0/content/

For example, the docs for "manipulation" you can find here:

https://github.com/svgdotjs/svgdotjs.github.io/blob/source-3.0/content/7-manipulating/default.txt

Best regards

**Comment by Fuzzyma** [comment]
Wow - 30minutes until the first one writes an issue. I guess thats new record :D.
Yes, I am fully aware of that - I updated the website with version selection and stuff and made overall deploying waaaay easier. For that purpose it was neccessary to delete the whole repository.
Then it took me a while to fix the last bugs and then I realized that github pages doesnt allow me to do php redirects and then the asset loading didnt work - and so on... :D 
It might take a while until https://svgjs.com is updated but https://svgdotjs.github.io should work now

**Comment by Fuzzyma** [comment]
Alright, everything up and working again :)

**Comment by d4h0** [comment]
Awesome :)

Btw.:

You may want to redirect from the old URLs to the new ones, if possible.

For example, if I search for "svg.js scale text" on Google there is a result for the "Manipulation" page that links to the URL "https://svgjs.com/manipulating/" (which doesn't exist).

This is not only bad for people who search for information about svg.js but also for svg.js's SEO / Marketing.

A "301 Moved Permanently" redirect seems to be best.

Search for "permanent redirect for seo" to find out how to do this, and why it's important.

**Comment by Fuzzyma** [comment]
Not possible. Github pages only allow for static files. I cannot redirect anywhere. Google will hopefullly soon crawl the site and update it accordingly
