### ISSUE TITLE
algolia stop working for 2.7 docs

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svgdotjs.github.io#89]
I want to finally finish https://github.com/svgdotjs/svg.draw.js/tree/WIP_SVG.Point for SVG.js 2.7 and it's making it a little difficult since the algolia search is not working for the 2.7 branch.

I have not looked too deep into this but did found that @wout wrote some notes about it in #25. 
In fact, search is only working for 3.0 - neither 3.1 or 2.7.

I checked that the `<meta name="docsearch:version" content="[VERSION_NUMBER]">` is working, so not sure what goes wrong.

Perhaps the site structure for 2.7 and 3.1 differs from what algolia has?https://github.com/algolia/docsearch-configs/blob/master/configs/svgjs.json

**Comment by Fuzzyma** [comment]
Ah, right someone told me already that it is broken and I forgot...
I updated the docs so that they work for every version but I guess agolia didnt keep up with that. I have to look into it...

**Comment by Fuzzyma** [comment]
Hopefully fixed with https://github.com/algolia/docsearch-configs/pull/1886

**Comment by Fuzzyma** [comment]
Jep - works. Thanks for the headsup :)

**Comment by dotnetCarpenter** [comment]
Thanks @Fuzzyma. You are a hero! 🎉

**Comment by Fuzzyma** [comment]
@dotnetCarpenter I see you working like crazy on your PR for svg.draw.js. I dont want to stop your eager but this plugin might get a full rework soon. So dont put to much effort into it, ok? :)

**Comment by dotnetCarpenter** [comment]
That is ok. I am trying out a lot of stuff to be sure the changes are
useful in real projects. but in the end I think my changes will be very
small. It is difficult however, to see how this will not be a SEMVER major
change. But I will write down lots of observations that might be useful for
you as a kind of a guide, when you rework the plugin. It is mostly in the
style of, "if you emit this SVG.Class, then be sure that this function
takes the same SVG.Class, so you can use it like so and so [examples]".

At the moment I'm busy with offline stuff but also learning Elm in the hope
of copying some ideas for the plugin examples. I also did some cleanup of
the repo and would like to suggest that the demos are a folder instead of a
branch but that can be split out to another PR.. I'll write everything down
and post it later.

**Comment by Fuzzyma** [comment]
Sounds great! When the rework is done, it has to be a new major version anyway because it wont work with 2.7 anymore. I am excited to see what you have in mind :)
