### ISSUE TITLE
Add examples for animating shapes along a path

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svgdotjs.github.io#9]
In https://github.com/svgdotjs/svg.js/issues/666 we got a question about _Moving an element along path_ and @Fuzzyma made some great examples.

1. https://jsfiddle.net/dotnetCarpenter/vceakozz/
2. https://jsfiddle.net/Fuzzy/vceakozz/3/

We should put that in our documentation. Number 1 is simpler than no. 2. It would make sense to keep the examples in that order, so the reader can follow the progress. Number 2 also features an important gotcha (that we can not fix in 2.x without creating a breaking change), for 2.x users.

>Note that in this example we have to wrap `pointAt` into `SVG.Point` because that function wrongly returns a native `SVGPoint` and not `SVG.Point`

**Comment by wout** [comment]
Changed **Tutorials** in **Tutorials / Examples** and added them there.
