### ISSUE TITLE
site error on svgjs.com

### ISSUE THREAD

**Issue by bsmaran** [svgdotjs/svgdotjs.github.io#91]
The svgjs.com website is experiencing an error when clicking on any of the plugins. Error 404 will occur.
Start link https://svgjs.com/docs/3.0/plugins/

**Comment by Fuzzyma** [comment]
Thanks for reporting. I will fix the links!

As a quickfix just google the names of the plugins and their repo should show up :)

**Comment by Fuzzyma** [comment]
finally done
