### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by edent** [svgdotjs/svgdotjs.github.io#98]
A few links go to a broken page - https://svgjs.dev/docs/3.0/elements

```
- full support for opacity (link: /elements/#svg-mask text: masks) and (link: /elements/#svg-clippath text: clipping paths)
- (link: /elements/#svg-textpath text: text paths), even animated
- element (link: /parents/#svg-g text: groups)
- dynamic (link: /elements/#svg-gradient text: gradients) and (link: /elements/#svg-pattern text: patterns)
```

https://github.com/svgdotjs/svgdotjs.github.io/blob/source-3.1/content/1-home/default.txt#L59

**Comment by Nogbit** [comment]
Noticed this myself and attempting to follow the contrib steps to create a PR but the npm install step fails with v8 errors.

**Comment by leocaseiro** [comment]
1 year, and still having this issue.

**Comment by Fuzzyma** [comment]
took only 3 years lol... sorry for that. Its a one man show and especially docs are not the most fun part :D.
If you find more broken links, feel free to report!
